settings: 
  link: "http://www.railstutorial.org/"
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book" 
  news: "https://news.railstutorial.org/"
  contact: "https://news.railstutorial.org/contact"
  about: "https://news.railstutorial.org/about"
  author: "https://www.michaelhartl.com/"
